require 'swagger_helper'

RSpec.describe 'Api::V1::Game', type: :request do
  path '/api/v1/game' do
    post 'Create a new game' do
      tags 'Game'
      description <<~DESC
        Limitations:
        - (Required) Provide a username as the creator of the game
        - The game name is generated by the server
      DESC
      consumes 'application/json'
      parameter name: :game, in: :body, schema: {
        type: :object,
        properties: {
          username: { type: :string }
        },
        required: [ 'username' ]
      }

      response '201', 'game created' do
        let(:game) { { username: 'player1' } }
        run_test! do |response|
          data = JSON.parse(response.body)
          expect(data['game_id']).to be_an(Integer)

          created_game = Game.find(data['game_id'])
          expect(created_game.players.pluck(:username)).to eq([ 'player1' ])
          expect(created_game.name).to be_present
          expect(created_game.status).to eq('waiting')
          expect(created_game.game_players.last.ready?).to be_falsey
        end
      end

      response '422', 'invalid request' do
        let(:game) { { username: '' } }
        run_test!
      end
    end
  end

  path '/api/v1/game/{id}/players' do
    put 'Join a game' do
      tags 'Game'
      description <<~DESC
        Limitations:
        - (Required) Provide a username as the player joining the game
      DESC
      consumes 'application/json'
      parameter name: :id, in: :path, type: :integer
      parameter name: :username, in: :body, schema: {
        type: :object,
        properties: {
          username: { type: :string }
        },
        required: [ 'username' ]
      }

      response '200', 'player joined game' do
        let(:game) { Game.create(name: 'game1') }
        let(:id) { game.id }
        let(:username) { { username: 'player2' } }
        run_test! do |response|
          data = JSON.parse(response.body)
          expect(data['game_id']).to eq(game.id)

          game.reload
          expect(game.players.pluck(:username)).to eq([ 'player2' ])
        end
      end

      response '422', 'invalid request' do
        let(:game) { Game.create(name: 'game1') }
        let(:id) { game.id }
        let(:username) { { username: '' } }
        run_test!
      end
    end
  end
end
